language: cpp

dist: xenial
  
install:
  - sudo dpkg --add-architecture armhf
  - cat /etc/apt/sources.list
  - echo "deb [arch=armhf] http://ports.ubuntu.com/ xenial main universe" > /etc/apt/sources.list
  - cat /etc/apt/sources.list 
  - sudo apt-get install -y libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev
  - export PROJECT_DIR=$PWD
  - sudo apt-get update -qq
  - sudo apt-get install -qq tree
  - sudo apt-get install -y libboost-all-dev:armhf
#  - sudo apt-get install -y libboost-all-dev 
  - cd $HOME
  - git clone https://github.com/raspberrypi/tools rpi-tools
  - export PATH=$PATH:$HOME/rpi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin
  - export ARCH=arm
  - export CCPREFIX=$HOME/rpi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-
  - export CC=arm-linux-gnueabihf-gcc
  - export RPI_CROSS_COMPILE=true
  - cd $PROJECT_DIR
  - export CXX=arm-linux-gnueabihf-g++
  
script:
  - wget -O 0001-Support-boost-v1.66.patch.zip https://github.com/GENIVI/vsomeip/files/2244890/0001-Support-boost-v1.66.patch.zip
  - unzip 0001-Support-boost-v1.66.patch.zip
  - git apply 0001-Support-boost-v1.66.patch
  - mkdir build
  - cd build 
  - cmake -DENABLE_SIGNAL_HANDLING=1 ..
  - make 
  - make install
  